apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: chaosexperiments.chaos.io
spec:
  group: chaos.io
  names:
    kind: ChaosExperiment
    listKind: ChaosExperimentList
    plural: chaosexperiments
    singular: chaosexperiment
    shortNames:
      - chaos
      - ce
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - scenario
                - duration
              properties:
                scenario:
                  type: string
                  enum:
                    - PodKiller
                    - CpuStress
                    - NetworkDelay
                  description: Chaos scenario type
                duration:
                  type: integer
                  minimum: 1
                  description: Experiment duration in seconds
                targetNamespace:
                  type: string
                  description: Target namespace (optional)
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Succeeded
                    - Failed
                  description: Current experiment phase
                message:
                  type: string
                  description: Status message
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Scenario
          type: string
          jsonPath: .spec.scenario
        - name: Duration
          type: integer
          jsonPath: .spec.duration
        - name: Phase
          type: string
          jsonPath: .status.phase
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
